/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AthenticatedRouteImport } from './routes/_athenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AthenticatedRoomIdRouteImport } from './routes/_athenticated/room/$id'
import { Route as AthenticatedRoomCreateRouteImport } from './routes/_athenticated/room/create'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthSignUpIndexRouteImport } from './routes/auth/sign-up/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthenticatedRoute = AthenticatedRouteImport.update({
  id: '/_athenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AthenticatedRoomIdRoute = AthenticatedRoomIdRouteImport.update({
  id: '/room/$id',
  path: '/room/$id',
  getParentRoute: () => AthenticatedRoute,
} as any)
const AthenticatedRoomCreateRoute = AthenticatedRoomCreateRouteImport.update({
  id: '/room/create',
  path: '/room/create',
  getParentRoute: () => AthenticatedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/room/$id': typeof AthenticatedRoomIdRoute
  '/room/create': typeof AthenticatedRoomCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthIndexRoute
  '/room/$id': typeof AthenticatedRoomIdRoute
  '/room/create': typeof AthenticatedRoomCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_athenticated': typeof AthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/_athenticated/room/$id': typeof AthenticatedRoomIdRoute
  '/_athenticated/room/create': typeof AthenticatedRoomCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/'
    | '/room/$id'
    | '/room/create'
    | '/api/auth/$'
    | '/auth/sign-up/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/room/$id'
    | '/room/create'
    | '/api/auth/$'
    | '/auth/sign-up'
  id:
    | '__root__'
    | '/'
    | '/_athenticated'
    | '/auth'
    | '/auth/'
    | '/_athenticated/room/$id'
    | '/_athenticated/room/create'
    | '/api/auth/$'
    | '/auth/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AthenticatedRoute: typeof AthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_athenticated': {
      id: '/_athenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_athenticated/room/$id': {
      id: '/_athenticated/room/$id'
      path: '/room/$id'
      fullPath: '/room/$id'
      preLoaderRoute: typeof AthenticatedRoomIdRouteImport
      parentRoute: typeof AthenticatedRoute
    }
    '/_athenticated/room/create': {
      id: '/_athenticated/room/create'
      path: '/room/create'
      fullPath: '/room/create'
      preLoaderRoute: typeof AthenticatedRoomCreateRouteImport
      parentRoute: typeof AthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up/': {
      id: '/auth/sign-up/'
      path: '/sign-up'
      fullPath: '/auth/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AthenticatedRouteChildren {
  AthenticatedRoomIdRoute: typeof AthenticatedRoomIdRoute
  AthenticatedRoomCreateRoute: typeof AthenticatedRoomCreateRoute
}

const AthenticatedRouteChildren: AthenticatedRouteChildren = {
  AthenticatedRoomIdRoute: AthenticatedRoomIdRoute,
  AthenticatedRoomCreateRoute: AthenticatedRoomCreateRoute,
}

const AthenticatedRouteWithChildren = AthenticatedRoute._addFileChildren(
  AthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AthenticatedRoute: AthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
