/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AthenticatedRouteImport } from './routes/_athenticated'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AthenticatedAccountRouteImport } from './routes/_athenticated/account'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AthenticatedRoomIdRouteImport } from './routes/_athenticated/room.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiLivekitWebhookRouteImport } from './routes/api/livekit.webhook'

const AthenticatedRoute = AthenticatedRouteImport.update({
  id: '/_athenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AthenticatedAccountRoute = AthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AthenticatedRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AthenticatedRoomIdRoute = AthenticatedRoomIdRouteImport.update({
  id: '/room/$id',
  path: '/room/$id',
  getParentRoute: () => AthenticatedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLivekitWebhookRoute = ApiLivekitWebhookRouteImport.update({
  id: '/api/livekit/webhook',
  path: '/api/livekit/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/account': typeof AthenticatedAccountRoute
  '/contact': typeof PublicContactRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/': typeof AuthIndexRoute
  '/room/$id': typeof AthenticatedRoomIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/livekit/webhook': typeof ApiLivekitWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/account': typeof AthenticatedAccountRoute
  '/contact': typeof PublicContactRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth': typeof AuthIndexRoute
  '/room/$id': typeof AthenticatedRoomIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/livekit/webhook': typeof ApiLivekitWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_athenticated': typeof AthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_athenticated/account': typeof AthenticatedAccountRoute
  '/_public/contact': typeof PublicContactRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_public/': typeof PublicIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_athenticated/room/$id': typeof AthenticatedRoomIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/livekit/webhook': typeof ApiLivekitWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/account'
    | '/contact'
    | '/auth/sign-up'
    | '/auth/'
    | '/room/$id'
    | '/api/auth/$'
    | '/api/livekit/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/contact'
    | '/auth/sign-up'
    | '/auth'
    | '/room/$id'
    | '/api/auth/$'
    | '/api/livekit/webhook'
  id:
    | '__root__'
    | '/_athenticated'
    | '/_public'
    | '/auth'
    | '/_athenticated/account'
    | '/_public/contact'
    | '/auth/sign-up'
    | '/_public/'
    | '/auth/'
    | '/_athenticated/room/$id'
    | '/api/auth/$'
    | '/api/livekit/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AthenticatedRoute: typeof AthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiLivekitWebhookRoute: typeof ApiLivekitWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_athenticated': {
      id: '/_athenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_athenticated/account': {
      id: '/_athenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AthenticatedAccountRouteImport
      parentRoute: typeof AthenticatedRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_athenticated/room/$id': {
      id: '/_athenticated/room/$id'
      path: '/room/$id'
      fullPath: '/room/$id'
      preLoaderRoute: typeof AthenticatedRoomIdRouteImport
      parentRoute: typeof AthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/livekit/webhook': {
      id: '/api/livekit/webhook'
      path: '/api/livekit/webhook'
      fullPath: '/api/livekit/webhook'
      preLoaderRoute: typeof ApiLivekitWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AthenticatedRouteChildren {
  AthenticatedAccountRoute: typeof AthenticatedAccountRoute
  AthenticatedRoomIdRoute: typeof AthenticatedRoomIdRoute
}

const AthenticatedRouteChildren: AthenticatedRouteChildren = {
  AthenticatedAccountRoute: AthenticatedAccountRoute,
  AthenticatedRoomIdRoute: AthenticatedRoomIdRoute,
}

const AthenticatedRouteWithChildren = AthenticatedRoute._addFileChildren(
  AthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicContactRoute: typeof PublicContactRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicContactRoute: PublicContactRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AuthRouteChildren {
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignUpRoute: AuthSignUpRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AthenticatedRoute: AthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiLivekitWebhookRoute: ApiLivekitWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
